--- #---------------- Orderer1 1Deployment ---------------
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: orderer1
  name: orderer1
  namespace: hyperledger
spec:
  selector:
    matchLabels:
      app: orderer1
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: orderer1
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: "app"
                      operator: In
                      values:
                        - orderer0
                        - orderer2
                topologyKey: "kubernetes.io/hostname"
      containers:
        - args:
            - "orderer"
          env:
            - name: FABRIC_LOGGING_SPEC
              value: DEBUG
            - name: ORDERER_OPERATIONS_LISTENADDRESS
              value: 0.0.0.0:8443
            - name: ORDERER_METRICS_PROVIDER
              value: prometheus
            - name: ORDERER_GENERAL_GENESISFILE
              value: /fabric/channel-artifacts/genesis.block
            - name: ORDERER_GENERAL_GENESISMETHOD
              value: file
            - name: ORDERER_GENERAL_LISTENADDRESS
              value: 0.0.0.0
            - name: ORDERER_GENERAL_LOCALMSPDIR
              value: /fabric/crypto-config/ordererOrganizations/consortium/orderers/orderer1/msp
            - name: ORDERER_GENERAL_LOCALMSPID
              value: OrdererMSP
            - name: ORDERER_GENERAL_TLS_CERTIFICATE
              value: /fabric/crypto-config/ordererOrganizations/consortium/orderers/orderer1/tls/server.crt
            - name: ORDERER_GENERAL_TLS_ENABLED
              value: "true"
            - name: ORDERER_GENERAL_TLS_PRIVATEKEY
              value: /fabric/crypto-config/ordererOrganizations/consortium/orderers/orderer1/tls/server.key
            - name: ORDERER_GENERAL_TLS_ROOTCAS
              value: "[/fabric/crypto-config/ordererOrganizations/consortium/orderers/orderer1/tls/ca.crt]"
            - name: ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE
              value: /fabric/crypto-config/ordererOrganizations/consortium/orderers/orderer1/tls/server.crt
            - name: ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY
              value: /fabric/crypto-config/ordererOrganizations/consortium/orderers/orderer1/tls/server.key
            - name: ORDERER_GENERAL_CLUSTER_ROOTCAS
              value: "[/fabric/crypto-config/ordererOrganizations/consortium/orderers/orderer1/tls/ca.crt]"
          image: hyperledger/fabric-orderer:amd64-2.2.0
          name: orderer
          ports:
            - containerPort: 7050
            - containerPort: 8443
          volumeMounts: 
          - mountPath: /fabric
            name: fabricfiles
      restartPolicy: Always
      volumes:
      - name: fabricfiles
        persistentVolumeClaim:
          claimName: pvc
        
        
        
        
        # - name: orderer-persistentdata
        #   hostPath:
        #     path: /home/storage/orderer
        #     type: DirectoryOrCreate
        # - name: orderer-claim0
        #   hostPath:
        #     path: /fabric/channel-artifacts/genesis.block
        # - name: orderer-claim1
        #   hostPath:
        #     path: /fabric/crypto-config/ordererOrganizations/consortium/orderers/orderer1/msp
        # - name: orderer-claim2
        #   hostPath:
        #     path: /fabric/crypto-config/ordererOrganizations/consortium/orderers/orderer1/tls
